# Generated by Django 3.2.8 on 2023-11-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='identification_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/'),
        ),
    ]
